draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30.0
  combo_w: 28
  combo_h: 26
  dark_mode: auto
  
  qmk_keyboard: totem 
  
parse_config:
  raw_binding_map:
    "&sys_reset": "RST"
    "&bootloader": "BOOT"
    "&caps_word": "CAPS"
    "&kp LC(FSLH)": "Com."
    "&kp LC(C)": "Copy"
    "&kp LC(V)": "Paste"
    "&hm LGUI A": "A"
    "&hm LALT S": "S"
    "&hm LCTRL D": "D"
    "&hm LSHFT F": "F"
    "&hm RSHFT J": "J"
    "&hm RCTRL K": "K"
    "&hm RALT L": "L"
    "&hm RGUI SEMI": ";"
    "&lt SYS TAB": "SYS"
    "&lt NAV SPACE": "NAV"
    "&lt SYM TAB": "SYM"
    "&lt SYM RET": "SYM"
    "&lt NAV BSPC": "NAV"