draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30.0

parse_config:
  preprocess: true
  zmk_hold_tap_behaviors:
    - hm
  zmk_keycode_map:
    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: Alt
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shft
    RSHFT: Shft

    # Mappings for complex FR macros
    FR_ESC_CHAR: EscChr
    FR_FILE_SEP: FileSep
    FR_GROUP_SEP: GrpSep

    # French layout keys
    FR_A: A
    FR_B: B
    FR_C: C
    FR_D: D
    FR_E: E
    FR_F: F
    FR_G: G
    FR_H: H
    FR_I: I
    FR_J: J
    FR_K: K
    FR_L: L
    FR_M: M
    FR_N: N
    FR_O: O
    FR_P: P
    FR_Q: Q
    FR_R: R
    FR_S: S
    FR_T: T
    FR_U: U
    FR_V: V
    FR_W: W
    FR_X: X
    FR_Y: Y
    FR_Z: Z
    FR_N0: '0'
    FR_N1: '1'
    FR_N2: '2'
    FR_N3: '3'
    FR_N4: '4'
    FR_N5: '5'
    FR_N6: '6'
    FR_N7: '7'
    FR_N8: '8'
    FR_N9: '9'
    FR_SPACE: Space
    FR_EXCLAMATION: '!'
    FR_DOUBLE_QUOTES: '"'
    FR_HASH: '#'
    FR_DOLLAR: '$'
    FR_PERCENT: '%'
    FR_AMPERSAND: '&'
    FR_SINGLE_QUOTE: ''''
    FR_LEFT_PARENTHESIS: '('
    FR_RIGHT_PARENTHESIS: ')'
    FR_ASTERISK: '*'
    FR_PLUS: '+'
    FR_COMMA: ','
    FR_MINUS: '-'
    FR_PERIOD: '.'
    FR_SLASH: '/'
    FR_COLON: ':'
    FR_SEMICOLON: ';'
    FR_LESS_THAN: '<'
    FR_EQUAL: '='
    FR_GREATER_THAN: '>'
    FR_QUESTION: '?'
    FR_AT_SIGN: '@'
    FR_LEFT_BRACKET: '['
    FR_BACKSLASH: '\'
    FR_RIGHT_BRACKET: ']'
    FR_CARET: ^
    FR_UNDERSCORE: _
    FR_GRAVE: '`'
    FR_LEFT_BRACE: '{'
    FR_PIPE: '|'
    FR_RIGHT_BRACE: '}'
    FR_TILDE: '~'
    FR_POUND_SIGN: £
    FR_CURRENCY_SIGN: ¤
    FR_SECTION: §
    FR_UMLAUT: ¨
    FR_DEGREE: °
    FR_SUPER2: ²
    FR_MU: µ
    FR_A_GRAVE: à
    FR_C_CEDILLA: ç
    FR_E_GRAVE: è
    FR_E_ACUTE: é
    FR_U_GRAVE: ù
    FR_EURO: €