name: Generate keymap SVG

on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "keymap_drawer.config.yaml"

permissions:
  contents: write

jobs:
  keymap-drawer-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install keymap-drawer
        run: pip install keymap-drawer

      - name: Generate SVG
        run: |
          mkdir -p img
          
          keymap parse -c 10 -z config/my_totem.keymap > parsed_keymap.yaml
          
          sed -i 's/qmk_keyboard: "my_totem"/qmk_keyboard: "totem"/g' parsed_keymap.yaml

          sed -i 's/qmk_keyboard: my_totem/qmk_keyboard: totem/g' parsed_keymap.yaml

          keymap draw parsed_keymap.yaml -s keymap_drawer.config.yaml > img/totem.svg

          rm parsed_keymap.yaml

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update keymap layout image"
          file_pattern: img/*.svg